
language: c

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison

install:
- ./bootstrap.sh
- ./configure --enable-asan
- make

script:
- make check

after_failure:
- find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false
