
language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison
    - docbook2x
    - xmlto
    - texinfo
    - source-highlight
    - libxml2-utils
    - xsltproc
    - fop
  homebrew:
    packages:
    - flex
    - bison

script:
  - make check

after_failure:
  - find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;

jobs:
  include:
    - stage: test
      install:
        - ./bootstrap.sh
        - ./configure
        - make
    - stage: documentation
      language: shell
      script:
        - cd doc
        - make html
        - make pdf

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false
