
language: c

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - gfortran
    - flex
    - bison
    - docbook2x
    - xmlto
    - texinfo
    - source-highlight
    - libxml2-utils
    - xsltproc
    - fop
  homebrew:
    packages:
    - flex
    - bison

install:
  - ./bootstrap.sh
  - ./configure
  - make

script:
  - make check

jobs:
  include:
    - stage: test
      after_failure:
        - find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;
    - stage: documentation
      language: shell
      script:
        - make html
        - make pdf

notifications:
  email:
    on_success: change
    on_failure: always

sudo: false
