
language: c
dist: xenial
os: linux

env:
  global:
    - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
    - sourceline: "deb https://apt.kitware.com/ubuntu/ xenial main"
      key_url: "https://apt.kitware.com/keys/kitware-archive-latest.asc"
    packages:
    - cmake
    - flex
    - bison
    - docbook2x
    - xmlto
    - texinfo
    - source-highlight
    - libxml2-utils
    - xsltproc
    - fop
    - libgmp-dev
    - libglpk-dev
    - libarpack2-dev
    - libblas-dev
    - liblapack-dev
  homebrew:
    packages:
    - flex
    - bison
    - gmp
    - glpk

script:
  - make check

after_failure:
  - find tests/testsuite.dir -name testsuite.log -exec cat \{\} \;

jobs:
  include:
    - name: "Linux"
      os: linux
      install:
        - mkdir build
        - cd build
        - cmake .. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_VERIFY_FINALLY_STACK=1
        - make
    - name: "Linux external deps"
      os: linux
      dist: bionic
      install:
        - mkdir build
        - cd build
        - cmake .. -DIGRAPH_VERIFY_FINALLY_STACK=1
        - make
#    - name: "Linux x87"
#      os: linux
#      env:
#        - CFLAGS="-mfpmath=387" CXXFLAGS="-mfpmath=387"
#      install:
#        - ./bootstrap.sh
#        - ./configure --enable-verify-finally --with-external-glpk
#        - make
    - name: "macOS"
      os: osx
      install:
        - mkdir build
        - cd build
        - cmake .. -DIGRAPH_USE_INTERNAL_BLAS=1 -DIGRAPH_USE_INTERNAL_LAPACK=1 -DIGRAPH_USE_INTERNAL_ARPACK=1 -DIGRAPH_USE_INTERNAL_GLPK=1 -DIGRAPH_USE_INTERNAL_CXSPARSE=1 -DIGRAPH_VERIFY_FINALLY_STACK=1 -DUSE_SANITIZER=Address;Undefined
        - make
#    - name: "Documentation"
#      language: shell
#      os: linux
#      install:
#        - ./bootstrap.sh
#        - ./configure
#        - cd doc
#      script:
#        - make html
        - make pdf

notifications:
  email:
    on_success: change
    on_failure: always
